# 1- Import

In [56]:
import numpy as np

# 2- Create a numpy 5X5 matrix with ones at the borders & zeros inside.
![image.png](attachment:image.png)

In [57]:
m = np.ones((5,5))
m[1:4 ,1:4]=0
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 3- Create a 5X5 matrix where the first diagonal = 1, while the second diagonal = 2, while other values=3.
![image-2.png](attachment:image-2.png)

In [58]:
m= np.full((5,5),3)
for i in range(5):
  for j in range(5):
      if i == j:
        m[i][j]=1
        m[i][-j-1]=2


print(m)


[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]


# 4- Consider representing parameters & biases of  the following system of linear algebra using matrices & Vectors:
![image.png](attachment:image.png)

In [43]:
# write code here


# 5- Create two matrices with any values you like and stack them vertically

In [59]:
m1 = np.array([[1 ,2 ,3],
               [4 ,5 ,6],
               [7 ,8 ,9]])
m2 = np.array([[2 ,4 ,6],
               [8 ,10 ,12],
              [14 ,16 ,18]])
m = np.vstack((m1,m2))
print (m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
